export enum Constants {
    UPDATE_NOTES = 'UPDATE_NOTES',
    SELECT_NOTE = 'SELECT_NOTE',
    CHANGE_INPUTS_MODE = 'CHANGE_INPUTS_MODE',
    DELETE_NOTE = 'DELETE_NOTE',
    SELECT_DATE_SECTION = 'SELECT_DATE_SECTION',

}
